language: cpp
compiler:
  - gcc
  - clang
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -q build-essential
  - sudo apt-get install -q libgsl0-dev
  - sudo apt-get install -q openmpi-bin openmpi-dev
  - sudo apt-get install -q libboost-all-dev
script: ./bootstrap && CC="mpicc" CXX="mpicxx" ./configure && make -j2 && make check
